const SEED_PRODUCTS = [
  {
    id: 'gaming-headphones-x1',
    aliasId: 'headphones-001',
    name: 'Gaming Headphones X1',
    description: 'Pro spatial audio wireless gaming headset with AI noise-canceling mic and ultra-low latency.',
    category: 'electronics',
    listPrice: 2500,
    price: 2500,
    floorPrice: 2200,
    maxDiscountPercent: 12.0,
    maxNegotiationRounds: 3,
    negotiable: true,
    stock: 75,
    bundleRules: [
      {
        id: 'bundle-free-shipping',
        freeGift: 'Free Express Shipping & Gold-Plated Jack Adapter',
        freeGiftProductId: 'shipping-upgrade',
        thresholdPrice: 2200,
        description: 'Complimentary Free Express Shipping on orders settled at or above ₹2,200',
      }
    ],
    crossSellProducts: ['water-bottle'],
    upsellProducts: ['running-shoes'],
    active: true,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    attributes: {
      brand: 'ShieldAudio',
      connectivity: 'Wireless 2.4GHz / Bluetooth 5.3',
      color: 'Matte Obsidian',
    },
  },
  {
    id: 'running-shoes',
    aliasId: 'shoe-001',
    name: 'Running Shoes',
    description: 'Performance breathable running shoes with high-traction carbon-plate sole.',
    category: 'sports',
    listPrice: 2499,
    price: 2499,
    floorPrice: 2200,
    maxDiscountPercent: 12,
    maxNegotiationRounds: 3,
    negotiable: true,
    stock: 100,
    bundleRules: [
      {
        id: 'bundle-running-socks',
        freeGift: 'Sports Socks',
        freeGiftProductId: 'sports-socks',
        thresholdPrice: 2299,
        description: 'Complimentary high-traction sports socks on orders at or above ₹2,299',
      }
    ],
    crossSellProducts: ['sports-socks', 'water-bottle'],
    upsellProducts: ['gym-bag'],
    active: true,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    attributes: {
      brand: 'AeroStride',
      sizes: ['UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
      color: 'Phantom Black / Neon Shield',
    },
  },
  {
    id: 'sports-t-shirt',
    aliasId: 'tshirt-002',
    name: 'Sports T-Shirt',
    description: 'DryFit moisture-wicking athletic training t-shirt.',
    category: 'sports',
    listPrice: 899,
    price: 899,
    floorPrice: 799,
    maxDiscountPercent: 11.1,
    maxNegotiationRounds: 3,
    negotiable: true,
    stock: 150,
    bundleRules: [],
    crossSellProducts: ['sports-socks', 'water-bottle'],
    upsellProducts: ['running-shoes'],
    active: true,
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    attributes: {
      brand: 'ShieldAthletics',
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      material: 'Recycled Poly-Spandex',
    },
  },
  {
    id: 'gym-bag',
    aliasId: 'bag-003',
    name: 'Gym Bag',
    description: '45L waterproof duffel bag with dedicated ventilated sneaker compartment.',
    category: 'sports',
    listPrice: 1299,
    price: 1299,
    floorPrice: 1149,
    maxDiscountPercent: 12,
    maxNegotiationRounds: 3,
    negotiable: true,
    stock: 80,
    bundleRules: [
      {
        id: 'bundle-bag-bottle',
        freeGift: 'Water Bottle',
        freeGiftProductId: 'water-bottle',
        thresholdPrice: 1249,
        description: 'Free 750ml water bottle when closing at or above ₹1,249',
      }
    ],
    crossSellProducts: ['water-bottle', 'sports-socks'],
    upsellProducts: ['running-shoes'],
    active: true,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    attributes: {
      brand: 'ShieldArmour',
      capacityLiters: 45,
      waterproof: true,
    },
  },
  {
    id: 'sports-socks',
    aliasId: 'socks-004',
    name: 'Sports Socks',
    description: 'Arch-support anti-blister cushioned athletic crew socks (3-Pack).',
    category: 'sports',
    listPrice: 299,
    price: 299,
    floorPrice: 249,
    maxDiscountPercent: 16.7,
    maxNegotiationRounds: 2,
    negotiable: true,
    stock: 200,
    bundleRules: [],
    crossSellProducts: ['running-shoes'],
    upsellProducts: ['running-shoes'],
    active: true,
    imageUrl: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=800&q=80',
    attributes: {
      packCount: 3,
      material: 'Organic Cotton + Elastane',
    },
  },
  {
    id: 'water-bottle',
    aliasId: 'bottle-005',
    name: 'Water Bottle',
    description: '750ml double-wall vacuum insulated stainless steel sports flask.',
    category: 'sports',
    listPrice: 499,
    price: 499,
    floorPrice: 449,
    maxDiscountPercent: 10,
    maxNegotiationRounds: 2,
    negotiable: true,
    stock: 120,
    bundleRules: [],
    crossSellProducts: ['gym-bag', 'sports-t-shirt'],
    upsellProducts: ['gym-bag'],
    active: true,
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
    attributes: {
      capacityMl: 750,
      material: '18/8 Stainless Steel',
    },
  }
];

module.exports = {
  SEED_PRODUCTS,
};
